### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by jaykay12** [appteam-nith/Nimbus#62]
README.md file should be updated by someone from the first year of App Team NITH, so that, the other interested developers find it easy to contribute in the repo

@RamolaWeb assign @musukeshu for this task. As I remember, @sukhbir-singh personally assigned her the task.

**Comment by jaykay12** [comment]
@musukeshu 
Take help from these links while drafting the markdown file:
[https://github.com/appteam-nith/Hillffair/blob/master/README.md](url)
[https://github.com/CSEC-NITH/PrivacyShield/blob/master/README.md](url)

**Comment by musukeshu** [comment]
Yes sir

**Comment by sukhbir-singh** [comment]
done...
